### ISSUE TITLE
Invalid Date / RSS Feed

### ISSUE THREAD

**Issue by beli3ver** [sunainapai/makesite#10]
Hi,

maybe we could change the date in the feed to match these:

https://validator.w3.org/feed/docs/error/InvalidRFC2822Date.html

    <pubDate>Wed, 02 Oct 2002 08:00:00 EST</pubDate>

    <pubDate>Wed, 02 Oct 2002 13:00:00 GMT</pubDate>

    <pubDate>Wed, 02 Oct 2002 15:00:00 +0200</pubDate>

So this is a valid date.

**Comment by sunainapai** [comment]
Hi @beli3ver,

Thank you for reporting this issue.

Fixed in commit 99c8e268a6c2c75943e1069ff95a5d64e1e19908. In this fix, the date from the content filename is interpreted as a GMT date. This is only a quick-fix to get a valid RSS as per the standard. We should probably interpret this as a date in local timezone. I will give some thought to it and work on it later.
