### ISSUE TITLE
{{ base_path }} placeholder gets not replaced in content HTML files

### ISSUE THREAD

**Issue by jufickel** [sunainapai/makesite#12]
Thank you very much for makesite. Of all the static site generators I've tried, this one suites my requirements best.

I set a value for the `base_path` default param in `makefile.py`. For the `page.html` template in folder `layout` the param gets replaced as expected. However in any HTML file in folder `content` the placeholder remains untouched.

As a workaround I manually replaced the placeholder with the actual value.

Are placeholders not supported in content HTML pages?

**Comment by sunainapai** [comment]
Hi @jufickel, 

I am glad to know that this project suits your requirements.

Thank you for creating this issue. Populating placeholders in content files was not supported by design so that one could write the content freely without makesite interfering with it. However your requirement shows that populating placeholders in content files may be desirable in some cases. I have added support for it as an optional feature in commit 8195677cae913e2f964bf631d88f00a33e16bc24. Please refer to [README](https://github.com/sunainapai/makesite#readme) for more details about this. Quoting the relevant section from it for your convenience:

> By default, placeholders in content files are not populated during rendering. This behaviour is chosen so that you can write content freely without having to worry about makesite interfering with the content, i.e., you can write something like `{{ title }}` in the content and makesite would leave it intact by default.
>
> However if you do want to populate the placeholders in a content file, you need to specify a parameter named `render` with value of `yes`. This can be done in two ways:
>
>   - Specify the parameter in a header in the content file in the following manner:
>
>         
>
>   - Specify the parameter as a keyword argument in `make_pages` call.  For example:
>
>         blog_posts = make_pages('content/blog/*.md',
>                                 '_site/blog/{{ slug }}/index.html',
>                                 post_layout, blog='blog', render='yes',
>                                 **params)

**Comment by jufickel** [comment]
Thank you very much! :+1:
