### ISSUE TITLE
Are you accepting any new features?

### ISSUE THREAD

**Issue by jep** [sunainapai/makesite#15]
Are you open to accepting new features or improvements? If so, do you have any guidelines we should follow?

**Comment by sunainapai** [comment]
Hi @jep,

I am not accepting any new features because I want to keep this project as simple as possible. This project is only meant to be a quick-starter-kit for developers who want to develop their own static site generators. Someone who wants more features is free to fork this project and customize it as per their needs. However, I accept bug fixes and minor improvements that do not increase the scope of this project.

I expect the pull requests to follow the same coding and commit conventions that I have been following in this repo. Here are a few guidelines regarding this:

- Follow [these Git commit conventions](https://github.com/erlang/otp/wiki/writing-good-commit-messages) while writing Git commit mesages.
- Follow [PEP-8](https://www.python.org/dev/peps/pep-0008/) while editing `makesite.py`.
- Use only commands and options that are specified in [POSIX utilities](https://pubs.opengroup.org/onlinepubs/9699919799/idx/utilities.html) as much as possible while editing `Makefile`. Especially, avoid [Bashisms](https://mywiki.wooledge.org/Bashism) and GNUisms.
- Use only features specified in [POSIX make](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html) while editing `Makefile`. Especially, avoid GNU extensions.
