### ISSUE TITLE
Proposal: Good template engine

### ISSUE THREAD

**Issue by orsinium** [sunainapai/makesite#5]
Why do you not use some template engine like [Jinja2](http://jinja.pocoo.org/docs/2.10/) or built-in [string.Template](https://docs.python.org/2/library/string.html#template-strings)?

**Comment by kgaughan** [comment]
Even changing the `render()` function to this would be an improvement:
```
def render(template, **params):
    """Replace placeholders in template with values from params."""
    return re.sub(r'{{\s*([^}\s]+)\s*}}',
                  lambda match: params.get(match.group(1), match.group(0)),
                  template)
```
At least then you're only doing one pass over the template and won't end up with weird expansion artifacts.

**Comment by sunainapai** [comment]
Hi @kgaughan, Thank you for your suggestion on improving the `render` function. I find it clever and useful. Would it be possible for you to send a pull request for this change? If not, I can make this change in `makesite.py` myself. However I prefer that you send this change as a pull request so that you appear as the author of the commit that contains this change.

**Comment by kgaughan** [comment]
Sure! Shouldn't take long to do. I'll submit it shortly.

**Comment by sunainapai** [comment]
Thank you for the improved templating. I have merged it to the master branch.
